config/routes.rb
Rails.application.routes.draw do
  # Ruta de inicio de sesión (sign in)
  # devise_scope :user do
  #   root to: "users/sessions#new"
  # end
  
  get '/contact', to: 'contact#index'
  
  # Rutas para los controladores de Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get '/profile', to: 'users/registrations#show', as: 'user_profile'
  end

  # Ruta para mostrar los postulantes
  get '/applicants', to: 'applicants#index', as: 'applicants'

  # Rutas fuera de la restricción esteban
  resources :applications, only: [:index, :new, :create, :destroy]

  # Rutas dentro de la restricción esteban
  constraints lambda { |req| req.env['warden'].user&.esteban? } do
    resources :job_offers, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :applications, only: [:index, :create, :destroy, :new]
    end
    resources :users, only: [:new, :create, :update]
    resources :applicants, only: [:index]

    get '/users', to: 'users/registrations#index', as: 'user_index'
  end

  

  # Ruta para las ofertas laborales para usuarios normales
  resources :job_offers, only: [:index], constraints: lambda { |req| req.env['warden'].user&.normal? }
  resources :users, only: [:show]

  root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new 
      if user.esteban?
        can :manage, :all        
      else
        can :read, JobOffer
    end
  end
end



# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     user ||= User.new # guest user (not logged in)

#     # Abilities for all users, including guests
#     can :read, JobOffer

#     if user.esteban?
#       # Abilities for Esteban
#       can :manage, :all
#     elsif user.normal?
#       # Abilities for normal users
#       can :create, Application
#     end
#   end
# end

app/models/application.rb
class Application < ApplicationRecord
    belongs_to :user
    belongs_to :job_offer
    belongs_to :applicant, class_name: 'User', foreign_key: 'user_id'
    validates :user_id, uniqueness: { scope: :job_offer_id, message: 'Ya te has postulado a esta oferta laboral.' }


    after_create :notify_esteban

  private

  def notify_esteban    
    EstebanMailer.notify_application(self).deliver_now
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    has_many :applications
    has_many :applicants, through: :applications, source: :user
    belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
    belongs_to :posted_by, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :applications
  has_many :job_offers, foreign_key: :created_by_id
  has_many :publications, foreign_key: :posted_by_id
  has_one_attached :photo  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum role: { normal: 0, esteban: 1 }
  
  before_validation :set_default_role, on: :create
  
  attr_accessor :profile_picture

  validates :email, uniqueness: true

  private

  def set_default_role
    self.role ||= :normal
  end
       
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def _footer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _navbar
  end
end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/about/index.html.erb
<!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>About Us</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
            <img src="assets/img/about.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
            <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
            <p class="fst-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="bi bi-check-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
              <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
            </ul>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
            </p>

          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts section-bg">
      <div class="container">

        <div class="row counters">

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="1232" data-purecounter-duration="1" class="purecounter"></span>
            <p>Students</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="64" data-purecounter-duration="1" class="purecounter"></span>
            <p>Courses</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="42" data-purecounter-duration="1" class="purecounter"></span>
            <p>Events</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
            <p>Trainers</p>
          </div>

        </div>

      </div>
    </section><!-- End Counts Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Testimonials</h2>
          <p>What are they saying</p>
        </div>

        <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="assets/img/testimonials/testimonials-1.jpg" class="testimonial-img" alt="">
                  <h3>Saul Goodman</h3>
                  <h4>Ceo &amp; Founder</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="assets/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                  <h3>Sara Wilsson</h3>
                  <h4>Designer</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="assets/img/testimonials/testimonials-3.jpg" class="testimonial-img" alt="">
                  <h3>Jena Karlis</h3>
                  <h4>Store Owner</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="assets/img/testimonials/testimonials-4.jpg" class="testimonial-img" alt="">
                  <h3>Matt Brandon</h3>
                  <h4>Freelancer</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="assets/img/testimonials/testimonials-5.jpg" class="testimonial-img" alt="">
                  <h3>John Larson</h3>
                  <h4>Entrepreneur</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

  </main><!-- End #main -->

app/views/contact/index.html.erb
<!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Contáctanos</h2>   
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">      

      <div class="container" data-aos="fade-up">

        <div class="row mt-5">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Dirección:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>esteban@rrhhInterno</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Teléfono:</h4>
                <p>+1 5589 55488 55s</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Nombre" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Mail" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Asunto" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Mensaje" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Cargando</div>
                <div class="error-message"></div>
                <div class="sent-message">Tu mensaje ha sido enviado. Gracias!</div>
              </div>
              <div class="text-center"><button type="submit">Mensaje Enviado</button></div>
            </form>

          </div>

        </div>

      </div>
      <div class="container" data-aos="fade-up">
      <br>
      <div class="text-center">
      <h2>Cómo llegar</h2>
      </div>
      <br>
      <div data-aos="fade-up">
        <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
      </div>
      </div>
    </section><!-- End Contact Section -->

app/views/footer/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Gestion RRHH</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
  <h4>Enlaces útiles</h4>
  <ul>
    <li><i class="bx bx-chevron-right"></i><%= link_to "Home", root_path, class: "navbar-brand" %></li>    
    <% if user_signed_in? %>
      <% if current_user.esteban? %>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Agregar usuarios", new_user_registration_path %></li>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Nueva oferta", new_job_offer_path %></li>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Ofertas", job_offers_path %></li>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Postulantes", applicants_path %></li>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Postulaciones", applications_path %></li>
      <% else %>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Postulaciones", applications_path %></li>
        <li><i class="bx bx-chevron-right"></i> <%= link_to "Perfil", edit_user_registration_path %></li>
        <% if current_user.normal? %>          
            <li><i class="bx bx-chevron-right"></i> <%= link_to "Ofertas laborales", job_offers_path, class: "nav-link" %></li>          
        <% end %>
      <% end %>      
    <% end %>    
  </ul>
</div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Otros Servicios</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Únase a nuestro boletín Laboral</h4>            
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribete">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Leonel Clavijo</span></strong>. Todos los derechos reservados
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
          Designed by <strong><span>Leonel Clavijo</span></strong>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

app/views/shared/_navbar.html.erb
<!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><%= link_to "RRHH Interno", root_path, class: "navbar-brand" %></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <%
=begin%>
 <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href="index.html">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="courses.html">Courses</a></li>
          <li><a href="trainers.html">Trainers</a></li>
          <li><a href="events.html">Events</a></li>
          <li><a href="pricing.html">Pricing</a></li>

          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar --> 
<%
=end%>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                
                <% if user_signed_in? %>
                <% if current_user.esteban? %>
                    <li class="nav-item">
                    <%= link_to "Agregar usuarios", new_user_registration_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                    <%= link_to "Nueva oferta", new_job_offer_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                    <%= link_to "Ofertas", job_offers_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                    <%= link_to "Postulantes", applicants_path, class: "nav-link" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                    <%= link_to "Mis postulaciones", applications_path, class: "nav-link" %>
                    </li>
                    <li class="dropdown"><a href="#"><span>Perfil</span><i class="bi bi-chevron-down"></i></a>
                        <ul>
                          <li><%= link_to "Ver perfil", user_profile_path, class: "dropdown-item" %></li>
                          <li><%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %></li>
                        </ul>
                    </li>  
                    <% if current_user.normal? %>
                        <li class="nav-item">
                        <%= link_to "Ofertas laborales", job_offers_path, class: "nav-link" %>
                        </li>
                    <% end %>
                <% end %>
                <li class="nav-item">
                    <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "get-started-btn" %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Iniciar Sesión", user_session_path, class: "nav-link" %>
                </li>
                <% end %>
            </ul>
            </div>
        </div>
         <% if current_user %>
                            Hola Usuario:<%= current_user.role %>
            <% end %>
        </nav>
    </div>
  </header><!-- End Header -->

app/views/trainer/index.html.erb
<h1>Trainer#index</h1>
<p>Find me in app/views/trainer/index.html.erb</p>