config/routes.rb
Rails.application.routes.draw do
  # Ruta de inicio de sesión (sign in)
  # devise_scope :user do
  #   root to: "users/sessions#new"
  # end
  
  get '/contact', to: 'contact#index'
  
  # Rutas para los controladores de Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get '/profile', to: 'users/registrations#show', as: 'user_profile'
  end

  # Ruta para mostrar los postulantes
  get '/applicants', to: 'applicants#index', as: 'applicants'

  # Rutas fuera de la restricción esteban
  resources :applications, only: [:index, :new, :create, :destroy]

  # Rutas dentro de la restricción esteban
  constraints lambda { |req| req.env['warden'].user&.esteban? } do
    resources :job_offers, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :applications, only: [:index, :create, :destroy, :new]
    end
    resources :users, only: [:new, :create, :update]
    resources :applicants, only: [:index]

    get '/users', to: 'users/registrations#index', as: 'user_index'
  end

  

  # Ruta para las ofertas laborales para usuarios normales
  resources :job_offers, only: [:index], constraints: lambda { |req| req.env['warden'].user&.normal? }
  resources :users, only: [:show]

  root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new 
      if user.esteban?
        can :manage, :all        
      else
        can :read, JobOffer
    end
  end
end



# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     user ||= User.new # guest user (not logged in)

#     # Abilities for all users, including guests
#     can :read, JobOffer

#     if user.esteban?
#       # Abilities for Esteban
#       can :manage, :all
#     elsif user.normal?
#       # Abilities for normal users
#       can :create, Application
#     end
#   end
# end

app/models/application.rb
class Application < ApplicationRecord
    belongs_to :user
    belongs_to :job_offer
    belongs_to :applicant, class_name: 'User', foreign_key: 'user_id'
    validates :user_id, uniqueness: { scope: :job_offer_id, message: 'Ya te has postulado a esta oferta laboral.' }


    after_create :notify_esteban

  private

  def notify_esteban    
    EstebanMailer.notify_application(self).deliver_now
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    has_many :applications
    has_many :applicants, through: :applications, source: :user
    belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
    belongs_to :posted_by, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :applications
  has_many :job_offers, foreign_key: :created_by_id
  has_many :publications, foreign_key: :posted_by_id
  has_one_attached :photo  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum role: { normal: 0, esteban: 1 }
  
  before_validation :set_default_role, on: :create
  
  attr_accessor :profile_picture

  validates :email, uniqueness: true

  private

  def set_default_role
    self.role ||= :normal
  end
       
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_applicants
  # before_action :set_job_offer, only: [:index]

  def index
    @applications = current_user.applications.includes(:job_offer)

    if current_user.esteban?
      @users = User.all
    else
      set_job_offer
    end
  end

  private

  def set_applicants
    @applicants = Application.includes(:user, :job_offer).all
  end

  def set_job_offer
    @job_offer = JobOffer.find_by(id: params[:job_offer_id])

    if @job_offer.nil?
      redirect_to job_offers_path, alert: 'La oferta laboral no existe.'
    else
      @applicants = @job_offer.applications
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def _footer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _navbar
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/applicants/index.html.erb
<br>
<h1>Postulantes de la oferta laboral</h1>

<!-- ======= Popular Courses Section ======= -->
    <section id="popular-courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h1>Lista de Postulaciones</h1>
        </div>

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          <% if @applications.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Título de la oferta</th>        
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @applications.each do |application| %>
        <tr>
          <td><%= application.job_offer.title %></td>          
          <td>
            <%= link_to "Eliminar postulación", job_offer_application_path(application.job_offer, application), method: :delete, data: { confirm: "¿Estás seguro de eliminar esta postulación?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No has realizado postulaciones.</p>
<% end %>

<% if current_user.esteban? %>
  <h2>Postulantes</h2>

  <% if @applicants.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Título de la oferta</th>
          <th>Postulante</th>
          <th>Mail</th>
          <th>Fecha de nacimiento</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @applicants.each do |applicant| %>
          <tr>
            <td><%= applicant.job_offer.title %></td>
            <td><%= applicant.user.name %></td>
            <td><%= applicant.user.email %></td>
            <td><%= applicant.user.birthdate %></td>
            <td>
            <%= link_to "Eliminar postulación", job_offer_application_path(applicant.job_offer, applicant), method: :delete, data: { confirm: "¿Estás seguro de eliminar esta postulación?" }, class: "btn btn-danger" %>

          </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No hay postulantes para ninguna oferta laboral.</p>
  <% end %>
<% end %>
        </div>
      </div>
    </section><!-- End Popular Courses Section -->

<%= link_to "Volver a la oferta laboral", job_offers_path, class: "btn btn-secondary" %>