config/routes.rb
Rails.application.routes.draw do
  # Ruta de inicio de sesión (sign in)
  # devise_scope :user do
  #   root to: "users/sessions#new"
  # end
  
  get '/contact', to: 'contact#index'
  
  # Rutas para los controladores de Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  devise_scope :user do
    get '/profile', to: 'users/registrations#show', as: 'user_profile'
  end

  # Ruta para mostrar los postulantes
  get '/applicants', to: 'applicants#index', as: 'applicants'

  # Rutas fuera de la restricción esteban
  resources :applications, only: [:index, :new, :create, :destroy]

  # Rutas dentro de la restricción esteban
  constraints lambda { |req| req.env['warden'].user&.esteban? } do
    resources :job_offers, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :applications, only: [:index, :create, :destroy, :new]
    end
    resources :users, only: [:new, :create, :update]
    resources :applicants, only: [:index]

    get '/users', to: 'users/registrations#index', as: 'user_index'
  end

  

  # Ruta para las ofertas laborales para usuarios normales
  resources :job_offers, only: [:index], constraints: lambda { |req| req.env['warden'].user&.normal? }
  resources :users, only: [:show]

  root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new 
      if user.esteban?
        can :manage, :all        
      else
        can :read, JobOffer
    end
  end
end



# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     user ||= User.new # guest user (not logged in)

#     # Abilities for all users, including guests
#     can :read, JobOffer

#     if user.esteban?
#       # Abilities for Esteban
#       can :manage, :all
#     elsif user.normal?
#       # Abilities for normal users
#       can :create, Application
#     end
#   end
# end

app/models/application.rb
class Application < ApplicationRecord
    belongs_to :user
    belongs_to :job_offer
    belongs_to :applicant, class_name: 'User', foreign_key: 'user_id'
    validates :user_id, uniqueness: { scope: :job_offer_id, message: 'Ya te has postulado a esta oferta laboral.' }


    after_create :notify_esteban

  private

  def notify_esteban    
    EstebanMailer.notify_application(self).deliver_now
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    has_many :applications
    has_many :applicants, through: :applications, source: :user
    belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
    belongs_to :posted_by, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :applications
  has_many :job_offers, foreign_key: :created_by_id
  has_many :publications, foreign_key: :posted_by_id
  has_one_attached :photo  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum role: { normal: 0, esteban: 1 }
  
  before_validation :set_default_role, on: :create
  
  attr_accessor :profile_picture

  validates :email, uniqueness: true

  private

  def set_default_role
    self.role ||= :normal
  end
       
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def _footer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  #before_action :set_job_offer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_job_offer, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource



  # GET /job_offers or /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1 or /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers or /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully created." }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
  end
end

  def applications
    @job_offer = JobOffer.find(params[:id])
    @applications = @job_offer.applications
  end
  
  def apply
    @job_offer = JobOffer.find(params[:id])
    @application = Application.new
  end

  # PATCH/PUT /job_offers/1 or /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully updated." }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1 or /job_offers/1.json
  def destroy
    @job_offer.destroy

    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: "Job offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_offer_params
      params.require(:job_offer).permit(:title, :description, :salary)
    end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _navbar
  end
end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/job_offers/_form.html.erb
<!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">
        <div class="row"> 
          <div class="col-lg-8 mx-auto mt-lg-0">
            <br>
              <%= form_with(model: job_offer) do |f| %>
              <% if job_offer.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h2>
                    <ul>
                      <% job_offer.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %> 
              <div class="form-group mt-3">                 
                <%= f.label "Puesto", style: "display: block", class:"form-label" %>
                <%= f.text_field :title, class:'form-control' %>
              </div> 
              <div class="form-group mt-3"> 
                <%= f.label "Descripcion", style: "display: block", class:"form-label" %>
                <%= f.text_field :description, class:'form-control' %> 
              </div>
              <div class="form-group mt-3">
                <%= f.label "Sueldo", style: "display: block", class:"form-label" %>
                <%= f.number_field :salary, class:'form-control' %>
              </div>
              <br>            
                <div class="text-center">
                  <%= f.submit "Crear", class:'get-started-btn' %>
                </div>
              <% end %>    
          </div>
        </div>
      </div>
    </section><!-- End Contact Section -->

app/views/job_offers/_job_offer.html.erb
<div id="<%= dom_id job_offer %>">
  <p>
    <strong>Title:</strong>
    <%= job_offer.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job_offer.description %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job_offer.salary %>
  </p>

</div>

app/views/job_offers/apply.html.erb
<h1>Postular a la oferta laboral: <%= @job_offer.title %></h1>

<%= form_with(model: @application, url: job_offer_applications_path(@job_offer), method: :post) do |form| %>
  <!-- Aquí colocamos los campos del formulario de postulación -->
  <%= form.submit "Postular", class: "btn btn-primary" %>
<% end %>

app/views/job_offers/edit.html.erb
<h1>Editing job offer</h1>

<%= render "form", job_offer: @job_offer %>

<br>

<div>
  <%= link_to "Show this job offer", @job_offer %> |
  <%= link_to "Back to job offers", job_offers_path %>
</div>

app/views/job_offers/index.html.erb
<br>
<h1>Ofertas de trabajo</h1>

<!-- ======= Popular Courses Section ======= -->
    <section id="popular-courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h1>Ofertas de trabajo</h1>
        </div>

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          <% @job_offers.each do |job_offer| %>
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">
              
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h4><%= job_offer.title %></h4>
                  <p class="price">$<%= job_offer.salary %></p>
                </div>

                <h3><a href="course-details.html"><%= job_offer.title %></a></h3>
                <p><%= job_offer.description %></p>
                
                <div class="trainer d-flex justify-content-between align-items-center">
                  <div class="trainer-profile d-flex align-items-center">                    
                    <%= image_tag 'trainer-1.jpg', class:"img-fluid" %>
                    <span>Publicado por esteban</span>
                  </div>
                  <div class="trainer-rank d-flex align-items-center">
                    <i class="bx bx-user"></i>&nbsp;50
                    &nbsp;&nbsp;
                    <i class="bx bx-heart"></i>&nbsp;65
                  </div>
                </div>
                <% if current_user.esteban? %>
                  <%= link_to "Editar", edit_job_offer_path(job_offer), class: "btn btn-primary" %>
                <% end %>
                  <% if current_user.normal? %>
                  <div class="text-center">
                    <%= link_to "Postular", new_job_offer_application_path(job_offer), class: "btn btn-success btn-sm" %>
                  </div>  
                  <% end %>
              </div>
            </div>
          </div> <!-- End Course Item-->
          <% end %>
        </div>
      </div>
    </section><!-- End Popular Courses Section -->

app/views/job_offers/new.html.erb
<!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Nueva Oferta Laboral</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <%= render "form", job_offer: @job_offer %>
    <div>
    
  <%= link_to "ofertas", job_offers_path, class:'get-started-btn' %>
</div>

app/views/job_offers/show.html.erb
<h1><%= @job_offer.title %></h1>
<p><%= @job_offer.description %></p>

<% if current_user.normal? %>
  <%= button_to "Postular", job_offer_applications_path(@job_offer), method: :post, data: { confirm: "¿Estás seguro de postularte a esta oferta laboral?" }, class: "btn btn-primary" %>
<% end %>

<% if @job_offer.applications.any? %>
  <h2>Postulantes</h2>
  <ul>
    <% @job_offer.applications.each do |application| %>
      <li><%= application.user.email %></li>
    <% end %>
  </ul>
<% else %>
  <p>No hay postulantes para esta oferta laboral.</p>
<% end %>

<%= link_to "Volver a la lista de ofertas", job_offers_path, class: "btn btn-secondary" %>